name: Deploy to Prod
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version to deploy"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check if image exists
        run: |
          IMAGE="cr.yandex/${{ secrets.REESTR_ID }}/app:${{ github.event.inputs.version }}_latest"
          docker manifest inspect "$IMAGE" > /dev/null 2>&1 \
            || (echo "Image not found: $IMAGE" && exit 1)

      - name: SSH & Run container
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            docker pull cr.yandex/${{ secrets.REESTR_ID }}/app:${{ github.event.inputs.version }}_latest
            docker stop app || true
            docker rm app || true
            docker run -d --name app cr.yandex/${{ secrets.REESTR_ID }}/app:${{ github.event.inputs.version }}_latest

      - name: Comment on Issue
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ secrets.LAST_RELEASE_ISSUE }}
          body: |
            Deployed version ${{ github.event.inputs.version }}_latest to prod by ${{ github.actor }} on $(date -u +"%Y-%m-%d")
