name: PR Checks
on:
  pull_request:
    types: [opened, synchronize, reopened]

lint-and-test:
  runs-on: ubuntu-latest
  steps:
    - name: Lint & Test
      uses: ./.github/actions/lint-and-test
      with:
        node-version: "18"
