name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3

      - name: Настройка Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Сборка Docker-образа
        run: |
          docker build -t cr.yandex/${{ secrets.REESTR_ID }}/app:${{ github.run_number }} .
          docker tag cr.yandex/${{ secrets.REESTR_ID }}/app:${{ github.run_number }} cr.yandex/${{ secrets.REESTR_ID }}/app:${{ github.run_number }}_latest

      - name: Логин в Yandex Container Registry
        run: echo "${{ secrets.YCR_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex

      - name: Push Docker-образа в YCR
        run: |
          docker push cr.yandex/${{ secrets.REESTR_ID }}/app:${{ github.run_number }}
          docker push cr.yandex/${{ secrets.REESTR_ID }}/app:${{ github.run_number }}_latest

      - name: Деплой по SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "${{ secrets.YCR_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex

            docker stop my_app || true
            docker rm my_app || true

            docker rmi cr.yandex/${{ secrets.REESTR_ID }}/app:${{ github.run_number }}_latest || true

            docker pull cr.yandex/${{ secrets.REESTR_ID }}/app:${{ github.run_number }}_latest
